src/.vuepress/config.js

Navbar updates

---

src/guide/basics/headers.md

in line 15, the request spell error.

fixed spell error : reuest.token

---

src/en/guide/advanced/versioning.md
src/en/guide/basics/routing.md
src/en/guide/best-practices/blueprints.md

Documentation Part of https://github.com/sanic-org/sanic/pull/2047

GIT-2045: add documentation for blueprint group versioning

---

src/guide/basics/handlers.md

Typo ("HTTPResonse") in handlers.md

---

src/en/guide/deployment/running.md

I think you meant 'processors' here.

Doc fix: 'processes' -> 'processors'.

---

src/en/guide/basics/response.md
src/zh/guide/basics/response.md

fixes https://github.com/sanic-org/sanic/issues/2093

add missing await in the example for sanic.response.file

---

src/en/guide/how-to/sqlalchemy.md
src/zh/guide/how-to/sqlalchemy.md

adding missing imports from SQLAlchemy

add missing imports

---

src/en/guide/basics/cookies.md
src/zh/guide/basics/cookies.md

Found it here: https://sanicframework.org/en/guide/basics/cookies.html#writing
and here too: https://sanicframework.org/zh/guide/basics/cookies.html

Corrected a minor mistake in the docs 

---

src/en/guide/basics/headers.md
src/en/guide/basics/request.md

- Changed `user .g...` to `user .g...`
- Reworded sentence that repeated itself. 
This was sort of discussed in #general of the discord server
Let me know if I missed something :smile:

Fix typo and reword a sentence

---

src/en/guide/basics/tasks.md

When adding `tasks` before `app.run`, it is required to pass the
callable and not the `coroutine` object or else a warning is seen. Added
documentation for that.

Added documentation for creating tasks before `app.run`

---

src/zh/guide/deployment/nginx.md

A spelling mistake

---

src/en/guide/how-to/orm.md

Fix formatting in ORM.md

---

src/en/guide/basics/response.md
src/zh/guide/basics/response.md

如果不添加 await 会包下面的错误 RuntimeWarning: coroutine 'file_stream' was never awaited
添加await 不报错

修复await file_stream 文档错误

---

src/.vuepress/config.js
src/en/guide/release-notes/v21.9.md
src/zh/guide/release-notes/v21.9.md

Add 21.9 relsase note translation and fixed a broken link and some typos

Add 21.9 relsase note translation

---

src/en/guide/deployment/configuration.md

Doc update

---

src/.vuepress/locales/details/sidebar/sidebar_en.js
src/.vuepress/locales/details/sidebar/sidebar_zh.js
src/en/guide/deployment/docker.md
src/zh/guide/deployment/docker.md

Add Chinese documentation for docker deployment

Update docker.md of zh guide

---

src/.vuepress/locales/abstract/locale_abstract_zh.js
src/.vuepress/locales/details/locale_detail_ja.js
src/en/guide/advanced/signals.md
src/zh/guide/advanced/signals.md

Usage of Sanic signals with conditions was added, in both English and Chinese. Japanese and Korean translations are needed.
Some minor locale improves included.

Signal Conditions; Minor locale Improve

---

.gitignore
src/en/guide/deployment/running.md
src/en/guide/release-notes/v22.6.md

1. Fix the links to aioquic repo.
2. Add `.vscode` and `package-lock.json` to the `.gitignore` file.

Fix Links; Update `.gitignore`

---

src/zh/plugins/sanic-ext/templating.md

Chinese (and Japanese and Korean)version of the guide is outdated. 
Maybe we should add some warnings on outdated translated guide.

Add chinese translation of templating.md

---

src/.vuepress/locales/details/sidebar/sidebar_en.js
src/en/guide/deployment/caddy.md
src/en/guide/deployment/nginx.md

Major cleanup to Nginx deployment, also avoiding a problem of not being able to run the server without TLS certificates. And added Caddy, which is now getting popular, for good reasons.

Caddy Deployment added, Nginx rewritten

---

src/en/guide/deployment/inspector.md

typo: insect -> inspect in Inspector, Using in Production

---

src/en/guide/deployment/running.md

Adds the parameters `dev`, `auto_reload`, and `version`. Other rows were touched due to realignment.

Add additional `run` parameters

---

src/en/guide/basics/routing.md

I blame VSCode for the whitespace changes.

Add path traversal warning
